Loaded module: cuda/10.2
Loaded dependency [gcc/8.4.0]: binutils/2.34
Loaded dependency [python3/3.8.2]: gcc/8.4.0
Loaded module: python3/3.8.2
Traceback (most recent call last):
  File "webNet_noRes_ATCD4D_CIFAR100.py", line 56, in <module>
    temp = tl.decomposition.parafac(tl.tensor(cc), rank = 1)
  File "/zhome/d8/b/107547/.local/lib/python3.8/site-packages/tensorly/backend/__init__.py", line 161, in inner
    return _get_backend_method(name)(*args, **kwargs)
  File "/zhome/d8/b/107547/.local/lib/python3.8/site-packages/tensorly/backend/numpy_backend.py", line 14, in tensor
    return np.array(data, dtype=dtype)
  File "/zhome/d8/b/107547/.local/lib/python3.8/site-packages/torch/tensor.py", line 621, in __array__
    return self.numpy()
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
Loaded module: cuda/10.2
Loaded dependency [gcc/8.4.0]: binutils/2.34
Loaded dependency [python3/3.8.2]: gcc/8.4.0
Loaded module: python3/3.8.2
Traceback (most recent call last):
  File "webNet_noRes_ATCD4D_CIFAR100.py", line 56, in <module>
    temp = tl.decomposition.parafac(tl.tensor(cc), rank = 1)
  File "/zhome/d8/b/107547/.local/lib/python3.8/site-packages/tensorly/backend/__init__.py", line 161, in inner
    return _get_backend_method(name)(*args, **kwargs)
  File "/zhome/d8/b/107547/.local/lib/python3.8/site-packages/tensorly/backend/numpy_backend.py", line 14, in tensor
    return np.array(data, dtype=dtype)
  File "/zhome/d8/b/107547/.local/lib/python3.8/site-packages/torch/tensor.py", line 621, in __array__
    return self.numpy()
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
Loaded module: cuda/10.2
Loaded dependency [gcc/8.4.0]: binutils/2.34
Loaded dependency [python3/3.8.2]: gcc/8.4.0
Loaded module: python3/3.8.2
Traceback (most recent call last):
  File "webNet_noRes_ATCD4D_CIFAR100.py", line 56, in <module>
    temp = tl.decomposition.parafac(cc, rank = 1)
  File "/zhome/d8/b/107547/.local/lib/python3.8/site-packages/tensorly/decomposition/_cp.py", line 276, in parafac
    weights, factors = initialize_cp(tensor, rank, init=init, svd=svd,
  File "/zhome/d8/b/107547/.local/lib/python3.8/site-packages/tensorly/decomposition/_cp.py", line 61, in initialize_cp
    U, S, _ = svd_fun(unfold(tensor, mode), n_eigenvecs=rank)
  File "/zhome/d8/b/107547/.local/lib/python3.8/site-packages/tensorly/base.py", line 51, in unfold
    return T.reshape(T.moveaxis(tensor, mode, 0), (tensor.shape[mode], -1))
  File "/zhome/d8/b/107547/.local/lib/python3.8/site-packages/tensorly/backend/__init__.py", line 161, in inner
    return _get_backend_method(name)(*args, **kwargs)
  File "<__array_function__ internals>", line 5, in moveaxis
  File "/zhome/d8/b/107547/.local/lib/python3.8/site-packages/numpy/core/numeric.py", line 1472, in moveaxis
    result = transpose(order)
TypeError: transpose() received an invalid combination of arguments - got (list), but expected one of:
 * (name dim0, name dim1)
 * (int dim0, int dim1)

Loaded module: cuda/10.2
Loaded dependency [gcc/8.4.0]: binutils/2.34
Loaded dependency [python3/3.8.2]: gcc/8.4.0
Loaded module: python3/3.8.2
ic| cc: tensor([[[ 0.1014, -0.0941, -0.1139],
                 [ 0.0032,  0.0998, -0.1580],
                 [-0.0146,  0.0492, -0.1433]],
        
                [[ 0.1124,  0.0397, -0.1849],
                 [-0.1197, -0.1451,  0.1141],
                 [ 0.1366,  0.0194,  0.1217]],
        
                [[-0.1011, -0.1192, -0.1688],
                 [ 0.1389,  0.0369, -0.0610],
                 [ 0.1558,  0.0722,  0.1155]]], device='cuda:0')
Traceback (most recent call last):
  File "webNet_noRes_ATCD4D_CIFAR100.py", line 57, in <module>
    temp = tl.decomposition.parafac(cc, rank = 1)
  File "/zhome/d8/b/107547/.local/lib/python3.8/site-packages/tensorly/decomposition/_cp.py", line 276, in parafac
    weights, factors = initialize_cp(tensor, rank, init=init, svd=svd,
  File "/zhome/d8/b/107547/.local/lib/python3.8/site-packages/tensorly/decomposition/_cp.py", line 61, in initialize_cp
    U, S, _ = svd_fun(unfold(tensor, mode), n_eigenvecs=rank)
  File "/zhome/d8/b/107547/.local/lib/python3.8/site-packages/tensorly/base.py", line 51, in unfold
    return T.reshape(T.moveaxis(tensor, mode, 0), (tensor.shape[mode], -1))
  File "/zhome/d8/b/107547/.local/lib/python3.8/site-packages/tensorly/backend/__init__.py", line 161, in inner
    return _get_backend_method(name)(*args, **kwargs)
  File "<__array_function__ internals>", line 5, in moveaxis
  File "/zhome/d8/b/107547/.local/lib/python3.8/site-packages/numpy/core/numeric.py", line 1472, in moveaxis
    result = transpose(order)
TypeError: transpose() received an invalid combination of arguments - got (list), but expected one of:
 * (name dim0, name dim1)
 * (int dim0, int dim1)

Loaded module: cuda/10.2
Loaded dependency [gcc/8.4.0]: binutils/2.34
Loaded dependency [python3/3.8.2]: gcc/8.4.0
Loaded module: python3/3.8.2
ic| cc: tensor([[[ 0.1491,  0.0936,  0.1519],
                 [-0.0667,  0.1024, -0.1543],
                 [-0.0529, -0.0415, -0.1827]],
        
                [[ 0.0921, -0.1667, -0.0828],
                 [ 0.1457, -0.0185,  0.1652],
                 [-0.1706,  0.1554, -0.0642]],
        
                [[ 0.1588, -0.1332,  0.1595],
                 [ 0.1771,  0.1893,  0.1765],
                 [ 0.0655, -0.0819,  0.0699]]], device='cuda:0')
Traceback (most recent call last):
  File "webNet_noRes_ATCD4D_CIFAR100.py", line 57, in <module>
    temp = tl.decomposition.parafac(cc, rank = 10)
  File "/zhome/d8/b/107547/.local/lib/python3.8/site-packages/tensorly/decomposition/_cp.py", line 276, in parafac
    weights, factors = initialize_cp(tensor, rank, init=init, svd=svd,
  File "/zhome/d8/b/107547/.local/lib/python3.8/site-packages/tensorly/decomposition/_cp.py", line 61, in initialize_cp
    U, S, _ = svd_fun(unfold(tensor, mode), n_eigenvecs=rank)
  File "/zhome/d8/b/107547/.local/lib/python3.8/site-packages/tensorly/base.py", line 51, in unfold
    return T.reshape(T.moveaxis(tensor, mode, 0), (tensor.shape[mode], -1))
  File "/zhome/d8/b/107547/.local/lib/python3.8/site-packages/tensorly/backend/__init__.py", line 161, in inner
    return _get_backend_method(name)(*args, **kwargs)
  File "<__array_function__ internals>", line 5, in moveaxis
  File "/zhome/d8/b/107547/.local/lib/python3.8/site-packages/numpy/core/numeric.py", line 1472, in moveaxis
    result = transpose(order)
TypeError: transpose() received an invalid combination of arguments - got (list), but expected one of:
 * (name dim0, name dim1)
 * (int dim0, int dim1)

Loaded module: cuda/10.2
Loaded dependency [gcc/8.4.0]: binutils/2.34
Loaded dependency [python3/3.8.2]: gcc/8.4.0
Loaded module: python3/3.8.2
Traceback (most recent call last):
  File "webNet_noRes_ATCD4D_CIFAR100.py", line 53, in <module>
    temp = tl.decomposition.parafac(tl.tensor(convData), rank = 10)
  File "/zhome/d8/b/107547/.local/lib/python3.8/site-packages/tensorly/backend/__init__.py", line 161, in inner
    return _get_backend_method(name)(*args, **kwargs)
  File "/zhome/d8/b/107547/.local/lib/python3.8/site-packages/tensorly/backend/numpy_backend.py", line 14, in tensor
    return np.array(data, dtype=dtype)
  File "/zhome/d8/b/107547/.local/lib/python3.8/site-packages/torch/tensor.py", line 621, in __array__
    return self.numpy()
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
Loaded module: cuda/10.2
Loaded dependency [gcc/8.4.0]: binutils/2.34
Loaded dependency [python3/3.8.2]: gcc/8.4.0
Loaded module: python3/3.8.2
Traceback (most recent call last):
  File "webNet_noRes_ATCD4D_CIFAR100.py", line 53, in <module>
    temp = tl.decomposition.parafac(convData, rank = 10)
  File "/zhome/d8/b/107547/.local/lib/python3.8/site-packages/tensorly/decomposition/_cp.py", line 276, in parafac
    weights, factors = initialize_cp(tensor, rank, init=init, svd=svd,
  File "/zhome/d8/b/107547/.local/lib/python3.8/site-packages/tensorly/decomposition/_cp.py", line 61, in initialize_cp
    U, S, _ = svd_fun(unfold(tensor, mode), n_eigenvecs=rank)
  File "/zhome/d8/b/107547/.local/lib/python3.8/site-packages/tensorly/base.py", line 51, in unfold
    return T.reshape(T.moveaxis(tensor, mode, 0), (tensor.shape[mode], -1))
  File "/zhome/d8/b/107547/.local/lib/python3.8/site-packages/tensorly/backend/__init__.py", line 161, in inner
    return _get_backend_method(name)(*args, **kwargs)
  File "<__array_function__ internals>", line 5, in moveaxis
  File "/zhome/d8/b/107547/.local/lib/python3.8/site-packages/numpy/core/numeric.py", line 1472, in moveaxis
    result = transpose(order)
TypeError: transpose() received an invalid combination of arguments - got (list), but expected one of:
 * (name dim0, name dim1)
 * (int dim0, int dim1)

Loaded module: cuda/10.2
Loaded dependency [gcc/8.4.0]: binutils/2.34
Loaded dependency [python3/3.8.2]: gcc/8.4.0
Loaded module: python3/3.8.2
<<<<<<< HEAD
Loaded module: cuda/10.2
Loaded dependency [gcc/8.4.0]: binutils/2.34
Loaded dependency [python3/3.8.2]: gcc/8.4.0
Loaded module: python3/3.8.2
Traceback (most recent call last):
  File "webNet_noRes_ATCD4D_CIFAR100.py", line 50, in <module>
    running_loss = train_net_PARAFAC4D_ATDC(losses, net, "net", trainloader, criterion, optimizer, convName, pqtu_convs, alpha, rank, lName, bName)
NameError: name 'bName' is not defined
=======
Traceback (most recent call last):
  File "webNet_noRes_ATCD4D_CIFAR100.py", line 53, in <module>
    ic(conData)
NameError: name 'conData' is not defined
<<<<<<< HEAD
Loaded module: cuda/10.2
Loaded dependency [gcc/8.4.0]: binutils/2.34
Loaded dependency [python3/3.8.2]: gcc/8.4.0
Loaded module: python3/3.8.2
Traceback (most recent call last):
  File "webNet_noRes_ATCD4D_CIFAR100.py", line 53, in <module>
    ic(conData)
NameError: name 'conData' is not defined
Loaded module: cuda/10.2
Loaded dependency [gcc/8.4.0]: binutils/2.34
Loaded dependency [python3/3.8.2]: gcc/8.4.0
Loaded module: python3/3.8.2
=======
>>>>>>> 23da4ca8f1479e2159c22c29b19c4904bec3433e
>>>>>>> aa9dd1f066e8be8e265aa5ccda7ea4971b069845
